interview/urls.py
from django.contrib import admin
from django.urls import path, include
from .routers import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('interviewapp.urls', namespace='interviewapp')),
]

interviewapp/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *

app_name = 'interviewapp'

urlpatterns = [
    path('', home, name='home'),
    path('programming-languages/', ProgrammingLanguageList.as_view(), name='programming_language_list'),
    path('languages/', LanguageList.as_view(), name='language_list'),
    path('developer/', DeveloperSearch.as_view(), name='developer_list'),
    path('interview/', interview, name='interview'),
    path('search-developer/', search_developer, name='search_developer')
]

urlpatterns = format_suffix_patterns(urlpatterns)

interviewapp/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# def validate_even(value):
#     if value >= 1 and value <=5 :
#         pass
#     else:
#         raise ValidationError(
#             _('%(value)s is not an even number'),
#             params={'value': value},)

# Create your models here.
class ProgrammingLanguage(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)

    def __str__(self):
        return self.name


class Language(models.Model):
    code = models.CharField(max_length=255, blank=False, null=False)

    def __str__(self):
        return self.code


class Developer(models.Model):
    email = models.EmailField(blank=False, null=False)
    programming_language = models.ManyToManyField(ProgrammingLanguage)
    language = models.ManyToManyField(Language)

    def __str__(self):
        return self.email


class Interview(models.Model):
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)
    score = models.PositiveIntegerField(default=3, validators=[MinValueValidator(1), MaxValueValidator(5)], blank=False, null=False)
    # score = models.PositiveIntegerField(default=3, validators=[validate_even], blank=False, null=False)
    comment = models.TextField(max_length=1000, blank=True, null=True)

    def __str__(self):
        return self.developer.email

interviewapp/views.py
from django.db.models import Count
from django.shortcuts import render
from rest_framework import generics

from .serializers import *
from .models import *


def home(request):
    return render(request, 'interviewapp/public.html')


def search_developer(request):
    return render(request, 'interviewapp/index.html')


def interview(request):
    return render(request, 'interviewapp/interview.html')


class ProgrammingLanguageList(generics.ListAPIView):
    serializer_class = ProgrammingLanguageSerializer

    def get_queryset(self):
        """
        This view should return a list of programming languages
        """
        q = '='
        if self.request.query_params and self.request.query_params['term'] != '':
            q = self.request.query_params['term']

        return ProgrammingLanguage.objects.filter(name__icontains=q)


class LanguageList(generics.ListAPIView):
    serializer_class = LanguageSerializer

    def get_queryset(self):
        """
        This view should return a list of languages
        """
        q = '='
        if self.request.query_params and self.request.query_params['term'] != '':
            q = self.request.query_params['term']

        result = Language.objects.filter(code__icontains=q)
        return result


class DeveloperSearch(generics.ListAPIView):
    serializer_class = DeveloperReadSerializer

    def get_queryset(self):
        """
        This view should return a list developer
        """

        query_pl = self.request.query_params.getlist('progLang[]', None)
        query_l = self.request.query_params.getlist('lang[]', None)

        # query_pl = ['javascript']
        # query_l = ['jp']

        if len(query_l) == 0 and len(query_pl) == 0:
            result = {}
        elif len(query_l) == 0 and len(query_pl) != 0:
            len_p_l = len(query_pl)
            result = Developer.objects \
                .filter(programming_language__name__in=query_pl) \
                .annotate(num_prog_lang=Count('programming_language')) \
                .filter(num_prog_lang__gte=len_p_l)
        elif len(query_pl) == 0 and len(query_l) != 0:
            len_l = len(query_l)
            result = Developer.objects \
                .filter(language__code__in=query_l) \
                .annotate(num_langs=Count('language')) \
                .filter(num_langs__gte=len_l)
        else:
            len_p_l = len(query_pl)
            len_l = len(query_l)
            result = Developer.objects \
                                    .filter(programming_language__name__in=query_pl, language__code__in=query_l) \
                                    .annotate(num_prog_lang=Count('programming_language'), num_langs=Count('language')) \
                                    .filter(num_prog_lang__gte=len_p_l, num_langs__gte=len_l)

        return result

interviewapp/templates/interviewapp/index.html
{% extends "interviewapp/public/base.html" %}
{% load staticfiles %}

{% block content %}

    <div class="container">
        <div style="height: 25px"></div>
        <div style="height: 100px"><a href="{% url 'interviewapp:home' %}" class="btn btn-primary btn-lg">Home</a><a href="{% url 'interviewapp:interview' %}" class="btn btn-primary btn-lg">Admin(Interview)</a><a href="{% url 'admin:index' %}" class="btn btn-primary btn-lg">Admin Site</a></div>


        <div class="form-group">
            <label for="progLang">Programming Language</label>
            <select class="progLang-ajax" style="width:50%" multiple="multiple"></select>
        </div>

        <div class="form-group">
            <label for="progLang">Language</label>
            <select class="lang-ajax " style="width:50%" multiple="multiple"></select>
        </div>

{#        <button type="submit" id="btnSearch" onclick="searchDev()" class="btn btn-primary">Submit</button>#}
        <button type="submit" id="btnSearch" data-bind="click: $data.addDeveloper" class="btn btn-primary">Submit</button>

    </div>



    <div class="border-light mb-12">
        <div class="card-body">
            <h4 class="card-title">Search result</h4>
            <table class="table table-hover" id="test">
                <thead>
                <tr>
                    <th scope="col">SN</th>
                    <th scope="col">Developer</th>
                    <th scope="col">Programming Language</th>
                    <th scope="col">Language</th>
                </tr>
                </thead>
                <tbody data-bind="foreach: developer" >

                    <tr>
                        <th scope="row" data-bind="text: id"></th>
                        <td data-bind="text: email"></td>
                        <td data-bind="foreach: programming_language"><!-- ko if: $index() > 0 -->,<!-- /ko --><span data-bind="text: name"></span></td>
                        <td data-bind="foreach: language"><!-- ko if: $index() > 0 -->,<!-- /ko --><span data-bind="text: code"></span></td>
                    </tr>

                </tbody>
            </table>

        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js"></script>

    <script src="{% static "js/knockout-3.4.2.js" %}"></script>
    <script src="{% static "js/script.js" %}" defer="defer"></script>

{% endblock %}

interviewapp/templates/interviewapp/public.html
{% extends "interviewapp/public/base.html" %}
{% load staticfiles %}

{% block content %}

    <a href="{% url 'interviewapp:search_developer' %}" class="btn btn-primary btn-lg">Search Developer</a><br>
    <a href="{% url 'interviewapp:interview' %}" class="btn btn-primary btn-lg">Admin(Interview)</a>
    <a href="{% url 'admin:index' %}" class="btn btn-primary btn-lg">Admin Site</a>
<br><br><br>
    <h3>Admin Site login credentials</h3><br>

    <h6>username: admin</h6><br><h6>password: Asdf1234@_</h6>

{% endblock %}